name: Build & Publish Wheels

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"     # tag releases publish to PyPI (if you added that job)
  pull_request:

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64 (manylinux2014)
          - os: ubuntu-22.04
            env:
              CIBW_BUILD: "cp310-manylinux_x86_64 cp311-manylinux_x86_64 cp312-manylinux_x86_64 cp313-manylinux_x86_64"
              CIBW_BUILD_VERBOSITY: "3"
              CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2014"
              # Quiet warnings; keep your existing CMake flags intact
              CXXFLAGS: "-w -static-libstdc++ -static-libgcc"
              CFLAGS: "-w"

          # Windows AMD64 only
          - os: windows-2022
            env:
              CIBW_BUILD: "cp310-win_amd64 cp311-win_amd64 cp312-win_amd64 cp313-win_amd64"
              CIBW_BUILD_VERBOSITY: "3"
              CIBW_SKIP: "*-win32"     # ensure 32-bit is skipped
              CIBW_ARCHS_WINDOWS: "AMD64"
              # Silence warnings on MSVC; keep your build flags in CMake
              CL: "/W0"

          # macOS Intel (x86_64, macOS >= 10.13)
          - os: macos-13
            env:
              CIBW_BUILD: "cp310-macosx_x86_64 cp311-macosx_x86_64 cp312-macosx_x86_64 cp313-macosx_x86_64"
              CIBW_BUILD_VERBOSITY: "3"
              # These env vars are visible to scikit-build/CMake invoked by pip
              CIBW_ENVIRONMENT_MACOS: >-
                MACOSX_DEPLOYMENT_TARGET=10.13
                CMAKE_OSX_DEPLOYMENT_TARGET=10.13
                CMAKE_OSX_ARCHITECTURES=x86_64
                SKBUILD_CMAKE_ARGS="-DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13"
              # Require the right arch to be present in Mach-O
              CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delocate-wheel --require-archs x86_64 -w {dest_dir} -v {wheel}"
              CXXFLAGS: "-w"
              CFLAGS: "-w"

          # macOS Apple Silicon (arm64, macOS >= 11.0)
          - os: macos-14
            env:
              CIBW_BUILD: "cp310-macosx_arm64 cp311-macosx_arm64 cp312-macosx_arm64 cp313-macosx_arm64"
              CIBW_BUILD_VERBOSITY: "3"
              CIBW_ENVIRONMENT_MACOS: >-
                MACOSX_DEPLOYMENT_TARGET=11.0
                CMAKE_OSX_DEPLOYMENT_TARGET=11.0
                CMAKE_OSX_ARCHITECTURES=arm64
                SKBUILD_CMAKE_ARGS="-DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0"
              CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delocate-wheel --require-archs arm64 -w {dest_dir} -v {wheel}"
              CXXFLAGS: "-w"
              CFLAGS: "-w"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (host)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.*

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Store wheels (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ runner.os }}
          path: wheelhouse/*.whl

  upload_testpypi_on_push:
    needs: build_wheels
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels-Linux
          path: dist
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
          name: wheels-macOS
          path: dist
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
          name: wheels-Windows
          path: dist
        continue-on-error: true

      - name: Show built wheels
        run: ls -al dist || true

      - name: Publish to TestPyPI (dev builds)
        env:
          TWINE_NON_INTERACTIVE: 1
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          python -m pip install -U twine
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*.whl || true

  upload_pypi_on_tag:
    needs: build_wheels
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels-Linux
          path: dist
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
          name: wheels-macOS
          path: dist
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
          name: wheels-Windows
          path: dist
        continue-on-error: true

      - name: Show built wheels
        run: ls -al dist || true

      - name: Publish to PyPI
        env:
          TWINE_NON_INTERACTIVE: 1
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install -U twine
          twine upload dist/*.whl
